In [3]:
import pandas as pd

In [4]:
df =pd.read_csv('Walmart_customer_purchases.csv')
df.shape

(50000, 12)

In [5]:
df.head(10)

,Customer_ID,Age,Gender,City,Category,Product_Name,Purchase_Date,Purchase_Amount,Payment_Method,Discount_Applied,Rating,Repeat_Customer
0,84607c1f-910c-44d5-b89f-e1ee06dd34c0,49,Female,New Cynthia,Electronics,Smartphone,8/30/2024,253.26,Cash on Delivery,No,1,Yes
1,f2a81712-a73e-4424-8b39-4c615a0bd4ea,36,Other,Cruzport,Clothing,T-Shirt,12/21/2024,73.19,Debit Card,Yes,1,No
2,da9be287-8b0e-4688-bccd-1a2cdd7567c6,52,Male,Jeffreytown,Beauty,Perfume,12/26/2024,125.62,Credit Card,Yes,1,No
3,50ec6932-3ac7-492f-9e55-4b148212f302,47,Female,Jenniferburgh,Electronics,Smartwatch,11/4/2024,450.32,Credit Card,No,2,Yes
4,8fdc3098-fc75-4b0f-983c-d8d8168c6362,43,Other,Kingshire,Electronics,Smartphone,10/7/2024,369.28,Credit Card,Yes,2,Yes
5,fdf82943-1b5f-4e0a-bf42-9a8e2035924e,59,Female,North Josemouth,Electronics,Laptop,2/15/2024,435.48,Cash on Delivery,No,3,No
6,582e8439-2b9b-46bd-93ff-71d610f455cc,47,Male,Johnsonton,Beauty,Perfume,12/19/2024,231.04,Debit Card,No,4,Yes
7,664555b7-7fd7-44a8-b4da-ec00230381b9,23,Other,Hoffmanmouth,Home,Sofa Cover,9/28/2024,240.91,Cash on Delivery,No,2,No
8,a8e37b6a-d34c-4d21-84fc-ef713d4859be,60,Female,South Billyberg,Beauty,Shampoo,1/30/2025,179.76,UPI,Yes,5,Yes
9,fa3bfd3a-99a4-41c7-bebc-8b04dc4c95f7,52,Female,North Katherinemouth,Home,Cookware,12/23/2024,463.43,Cash on Delivery,Yes,3,No

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       50000 non-null  str
 1   Age               50000 non-null  int64
 2   Gender            50000 non-null  str
 3   City              50000 non-null  str
 4   Category          50000 non-null  str
 5   Product_Name      50000 non-null  str
 6   Purchase_Date     50000 non-null  str
 7   Purchase_Amount   50000 non-null  float64
 8   Payment_Method    50000 non-null  str
 9   Discount_Applied  50000 non-null  str
 10  Rating            50000 non-null  int64
 11  Repeat_Customer   50000 non-null  str
dtypes: float64(1), int64(2), str(9)
memory usage: 4.6 MB

In [7]:
df.describe()

                Age  Purchase_Amount        Rating
count  50000.000000     50000.000000  50000.000000
mean      38.945220       255.532230      2.998680
std       12.398137       141.574416      1.417956
min       18.000000        10.010000      1.000000
25%       28.000000       133.050000      2.000000
50%       39.000000       255.045000      3.000000
75%       50.000000       378.912500      4.000000
max       60.000000       499.990000      5.000000

In [8]:
df.isnull().sum()

Customer_ID         0
Age                 0
Gender              0
City                0
Category            0
Product_Name        0
Purchase_Date       0
Purchase_Amount     0
Payment_Method      0
Discount_Applied    0
Rating              0
Repeat_Customer     0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns = df.columns.str.lower()
df.columns

Index(['customer_id', 'age', 'gender', 'city', 'category', 'product_name',
       'purchase_date', 'purchase_amount', 'payment_method',
       'discount_applied', 'rating', 'repeat_customer'],
      dtype='str')

In [11]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)
df[['age', 'age_group']].head(10)

   age    age_group
0   49  Middle-aged
1   36        Adult
2   52       Senior
3   47  Middle-aged
4   43  Middle-aged
5   59       Senior
6   47  Middle-aged
7   23  Young Adult
8   60       Senior
9   52       Senior

In [12]:
df.to_csv('Walmart_customer_purchases.csv', index= False)